target_node,root_cause_node,issue_type,severity,affected_column,paths,IssueNumber,DetailedPathDescription,timestamp,textual_representation,structured_textual_summary
PetSite,servi-petsi.us-west-2.elb.amazonaws.com_remote,latency,0.035435269,availability_Average,"['PetSite', 'servi-petsi.us-west-2.elb.amazonaws.com_remote']",0_39,The path of the issue is from PetSite to servi-petsi.us-west-2.elb.amazonaws.com_remote.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.04 was detected. Root Cause Node: servi-petsi.us-west-2.elb.amazonaws.com_remote, Target Node: PetSite, Affected Metric: availability_Average. Path: ['PetSite', 'servi-petsi.us-west-2.elb.amazonaws.com_remote']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.04, with 'servi-petsi.us-west-2.elb.amazonaws.com_remote' identified as the root cause and 'PetSite' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'servi-petsi.us-west-2.elb.amazonaws.com_remote']."
PetSite,servi-lista.us-west-2.elb.amazonaws.com_remote,latency,0.050744991,latency_p95,"['PetSite', 'servi-lista.us-west-2.elb.amazonaws.com_remote']",0_22,The path of the issue is from PetSite to servi-lista.us-west-2.elb.amazonaws.com_remote.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.05 was detected. Root Cause Node: servi-lista.us-west-2.elb.amazonaws.com_remote, Target Node: PetSite, Affected Metric: latency_p95. Path: ['PetSite', 'servi-lista.us-west-2.elb.amazonaws.com_remote']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.05, with 'servi-lista.us-west-2.elb.amazonaws.com_remote' identified as the root cause and 'PetSite' as the target. The affected metric was 'latency_p95'. The path involved: ['PetSite', 'servi-lista.us-west-2.elb.amazonaws.com_remote']."
PetSearch_AWS::ECS::Fargate,PetSearch_client,latency,0.084975801,latency_Average,"['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'S3_AWS::S3']",1_26,"The path of the issue is from PetSearch_client, through PetSearch_AWS::ECS::Fargate, to S3_AWS::S3.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.08 was detected. Root Cause Node: PetSearch_client, Target Node: PetSearch_AWS::ECS::Fargate, Affected Metric: latency_Average. Path: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'S3_AWS::S3']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.08, with 'PetSearch_client' identified as the root cause and 'PetSearch_AWS::ECS::Fargate' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'S3_AWS::S3']."
lambda_step_priceGreaterThan55_AWS::Lambda::Function,AWS::StepFunctions::StateMachine,latency,0.044869842,latency_p90,"['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55']",2_28,"The path of the issue is from AWS::StepFunctions::StateMachine, through lambda_step_priceGreaterThan55_AWS::Lambda to lambda_step_priceGreaterThan55_AWS::Lambda::Function, to lambda_step_priceGreaterThan55.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.04 was detected. Root Cause Node: AWS::StepFunctions::StateMachine, Target Node: lambda_step_priceGreaterThan55_AWS::Lambda::Function, Affected Metric: latency_p90. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.04, with 'AWS::StepFunctions::StateMachine' identified as the root cause and 'lambda_step_priceGreaterThan55_AWS::Lambda::Function' as the target. The affected metric was 'latency_p90'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55']."
lambda_step_readDDB,lambda_step_readDDB_AWS::Lambda::Function,latency,0.126535622,latency_p90,"['lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']",1_32,"The path of the issue is from lambda_step_readDDB_AWS::Lambda, through lambda_step_readDDB_AWS::Lambda::Function, to lambda_step_readDDB.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.13 was detected. Root Cause Node: lambda_step_readDDB_AWS::Lambda::Function, Target Node: lambda_step_readDDB, Affected Metric: latency_p90. Path: ['lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.13, with 'lambda_step_readDDB_AWS::Lambda::Function' identified as the root cause and 'lambda_step_readDDB' as the target. The affected metric was 'latency_p90'. The path involved: ['lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']."
petlistadoptions_AWS::ECS::Fargate,petlistadoptions_client,latency,0.108942408,latency_p99,"['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PGSQL Query_remote']",1_35,"The path of the issue is from petlistadoptions_client, through petlistadoptions_AWS::ECS::Fargate, to PGSQL Query_remote.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.11 was detected. Root Cause Node: petlistadoptions_client, Target Node: petlistadoptions_AWS::ECS::Fargate, Affected Metric: latency_p99. Path: ['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PGSQL Query_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.11, with 'petlistadoptions_client' identified as the root cause and 'petlistadoptions_AWS::ECS::Fargate' as the target. The affected metric was 'latency_p99'. The path involved: ['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PGSQL Query_remote']."
lambda_step_readDDB,lambda_step_readDDB_AWS::Lambda::Function,latency,0.081812351,latency_p99,"['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']",2_0,The path of the issue is from lambda_step_readDDB_AWS::Lambda::Function to lambda_step_readDDB.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.08 was detected. Root Cause Node: lambda_step_readDDB_AWS::Lambda::Function, Target Node: lambda_step_readDDB, Affected Metric: latency_p99. Path: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.08, with 'lambda_step_readDDB_AWS::Lambda::Function' identified as the root cause and 'lambda_step_readDDB' as the target. The affected metric was 'latency_p99'. The path involved: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']."
payforadoption_AWS::ECS::Container,lambdastatusupdater_AWS::Lambda,latency,0.108504052,latency_p50,"['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']",1_29,"The path of the issue is from payforadoption_AWS::ECS::Container, through PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage to lambdastatusupdater_AWS::Lambda to lambdastatusupdater_AWS::Lambda::Function, to petInfo_AWS::DynamoDB::Table.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.11 was detected. Root Cause Node: lambdastatusupdater_AWS::Lambda, Target Node: payforadoption_AWS::ECS::Container, Affected Metric: latency_p50. Path: ['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.11, with 'lambdastatusupdater_AWS::Lambda' identified as the root cause and 'payforadoption_AWS::ECS::Container' as the target. The affected metric was 'latency_p50'. The path involved: ['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']."
DynamoDB_AWS::DynamoDB,lambda_step_readDDB,latency,0.039321879,availability_Average,"['lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']",0_26,The path of the issue is from lambda_step_readDDB to DynamoDB_AWS::DynamoDB.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.04 was detected. Root Cause Node: lambda_step_readDDB, Target Node: DynamoDB_AWS::DynamoDB, Affected Metric: availability_Average. Path: ['lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.04, with 'lambda_step_readDDB' identified as the root cause and 'DynamoDB_AWS::DynamoDB' as the target. The affected metric was 'availability_Average'. The path involved: ['lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']."
PetSite,169.254.170.2_remote,latency,0.036742792,latency_p95,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']",0_15,"The path of the issue is from PetSite, through petlistadoptions_AWS::ECS::Fargate to PetSearch_AWS::ECS::Fargate, to 169.254.170.2_remote.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.04 was detected. Root Cause Node: 169.254.170.2_remote, Target Node: PetSite, Affected Metric: latency_p95. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.04, with '169.254.170.2_remote' identified as the root cause and 'PetSite' as the target. The affected metric was 'latency_p95'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']."
Servi-searc.us-west-2.elb.amazonaws.com_remote,PetSite,latency,0.035630486,availability_Average,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'Servi-searc.us-west-2.elb.amazonaws.com_remote']",1_41,"The path of the issue is from PetSite, through petlistadoptions_AWS::ECS::Fargate, to Servi-searc.us-west-2.elb.amazonaws.com_remote.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.04 was detected. Root Cause Node: PetSite, Target Node: Servi-searc.us-west-2.elb.amazonaws.com_remote, Affected Metric: availability_Average. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'Servi-searc.us-west-2.elb.amazonaws.com_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.04, with 'PetSite' identified as the root cause and 'Servi-searc.us-west-2.elb.amazonaws.com_remote' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'Servi-searc.us-west-2.elb.amazonaws.com_remote']."
PetSearch_AWS::ECS::Fargate,AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement,latency,0.052732872,availability_Average,"['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']",0_4,"The path of the issue is from petlistadoptions_AWS::ECS::Fargate, through PetSearch_AWS::ECS::Fargate, to AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.05 was detected. Root Cause Node: AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement, Target Node: PetSearch_AWS::ECS::Fargate, Affected Metric: availability_Average. Path: ['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.05, with 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement' identified as the root cause and 'PetSearch_AWS::ECS::Fargate' as the target. The affected metric was 'availability_Average'. The path involved: ['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']."
lambda_step_priceGreaterThan55_AWS::Lambda,Evidently_AWS::Evidently,latency,0.06827962,latency_Average,"['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']",0_38,"The path of the issue is from AWS::StepFunctions::StateMachine, through lambda_step_priceGreaterThan55_AWS::Lambda to lambda_step_priceGreaterThan55_AWS::Lambda::Function to lambda_step_priceGreaterThan55, to Evidently_AWS::Evidently.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.07 was detected. Root Cause Node: Evidently_AWS::Evidently, Target Node: lambda_step_priceGreaterThan55_AWS::Lambda, Affected Metric: latency_Average. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.07, with 'Evidently_AWS::Evidently' identified as the root cause and 'lambda_step_priceGreaterThan55_AWS::Lambda' as the target. The affected metric was 'latency_Average'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']."
adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL,payforadoption_AWS::ECS::Container,latency,0.055231557,latency_Average,"['payforadoption_AWS::ECS::Container', 'adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL']",2_19,The path of the issue is from payforadoption_AWS::ECS::Container to adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.06 was detected. Root Cause Node: payforadoption_AWS::ECS::Container, Target Node: adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL, Affected Metric: latency_Average. Path: ['payforadoption_AWS::ECS::Container', 'adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.06, with 'payforadoption_AWS::ECS::Container' identified as the root cause and 'adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL' as the target. The affected metric was 'latency_Average'. The path involved: ['payforadoption_AWS::ECS::Container', 'adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL']."
lambda_step_priceLessThan55_AWS::Lambda,AWS::StepFunctions::StateMachine,latency,0.123899119,latency_Average,"['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']",1_4,"The path of the issue is from StepFnStateMachine76D362E8-T67Tg48ke8oK_client, through AWS::StepFunctions::StateMachine to lambda_step_priceLessThan55_AWS::Lambda, to lambda_step_priceLessThan55_AWS::Lambda::Function.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.12 was detected. Root Cause Node: AWS::StepFunctions::StateMachine, Target Node: lambda_step_priceLessThan55_AWS::Lambda, Affected Metric: latency_Average. Path: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.12, with 'AWS::StepFunctions::StateMachine' identified as the root cause and 'lambda_step_priceLessThan55_AWS::Lambda' as the target. The affected metric was 'latency_Average'. The path involved: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']."
lambdastatusupdater_AWS::Lambda::Function,invalid_AWS::DynamoDB::Table,latency,0.06210741,latency_p99,"['lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'invalid_AWS::DynamoDB::Table']",0_12,"The path of the issue is from lambdastatusupdater_AWS::Lambda, through lambdastatusupdater_AWS::Lambda::Function, to invalid_AWS::DynamoDB::Table.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.06 was detected. Root Cause Node: invalid_AWS::DynamoDB::Table, Target Node: lambdastatusupdater_AWS::Lambda::Function, Affected Metric: latency_p99. Path: ['lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'invalid_AWS::DynamoDB::Table']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.06, with 'invalid_AWS::DynamoDB::Table' identified as the root cause and 'lambdastatusupdater_AWS::Lambda::Function' as the target. The affected metric was 'latency_p99'. The path involved: ['lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'invalid_AWS::DynamoDB::Table']."
lambda_step_readDDB,DynamoDB_AWS::DynamoDB,latency,0.091220169,latency_p50,"['AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']",0_13,"The path of the issue is from AWS::StepFunctions::StateMachine, through lambda_step_readDDB_AWS::Lambda to lambda_step_readDDB_AWS::Lambda::Function to lambda_step_readDDB, to DynamoDB_AWS::DynamoDB.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.09 was detected. Root Cause Node: DynamoDB_AWS::DynamoDB, Target Node: lambda_step_readDDB, Affected Metric: latency_p50. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.09, with 'DynamoDB_AWS::DynamoDB' identified as the root cause and 'lambda_step_readDDB' as the target. The affected metric was 'latency_p50'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']."
PetSite,AWS::StepFunctions::StateMachine,latency,0.096500346,latency_p99,"['PetSite', 'AWS::StepFunctions::StateMachine']",2_6,The path of the issue is from PetSite to AWS::StepFunctions::StateMachine.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.10 was detected. Root Cause Node: AWS::StepFunctions::StateMachine, Target Node: PetSite, Affected Metric: latency_p99. Path: ['PetSite', 'AWS::StepFunctions::StateMachine']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.10, with 'AWS::StepFunctions::StateMachine' identified as the root cause and 'PetSite' as the target. The affected metric was 'latency_p99'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine']."
PetSearch_client,PetSearch_AWS::ECS::Fargate,latency,0.089257065,availability_Average,"['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']",1_7,"The path of the issue is from PetSearch_client, through PetSearch_AWS::ECS::Fargate, to 169.254.170.2_remote.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.09 was detected. Root Cause Node: PetSearch_AWS::ECS::Fargate, Target Node: PetSearch_client, Affected Metric: availability_Average. Path: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.09, with 'PetSearch_AWS::ECS::Fargate' identified as the root cause and 'PetSearch_client' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']."
lambda_step_readDDB_AWS::Lambda,lambda_step_readDDB,latency,0.064120316,latency_Average,"['lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'SSM_AWS::SSM']",1_6,"The path of the issue is from lambda_step_readDDB_AWS::Lambda, through lambda_step_readDDB_AWS::Lambda::Function to lambda_step_readDDB, to SSM_AWS::SSM.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.06 was detected. Root Cause Node: lambda_step_readDDB, Target Node: lambda_step_readDDB_AWS::Lambda, Affected Metric: latency_Average. Path: ['lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'SSM_AWS::SSM']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.06, with 'lambda_step_readDDB' identified as the root cause and 'lambda_step_readDDB_AWS::Lambda' as the target. The affected metric was 'latency_Average'. The path involved: ['lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'SSM_AWS::SSM']."
AWS::StepFunctions::StateMachine,Evidently_AWS::Evidently,latency,0.060506775,latency_p99,"['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']",2_1,"The path of the issue is from AWS::StepFunctions::StateMachine, through lambda_step_priceGreaterThan55_AWS::Lambda to lambda_step_priceGreaterThan55_AWS::Lambda::Function to lambda_step_priceGreaterThan55, to Evidently_AWS::Evidently.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.06 was detected. Root Cause Node: Evidently_AWS::Evidently, Target Node: AWS::StepFunctions::StateMachine, Affected Metric: latency_p99. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.06, with 'Evidently_AWS::Evidently' identified as the root cause and 'AWS::StepFunctions::StateMachine' as the target. The affected metric was 'latency_p99'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']."
PetSite,AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement,latency,0.096312792,availability_Average,"['PetSite', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']",1_0,"The path of the issue is from PetSite, through PetSearch_AWS::ECS::Fargate, to AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.10 was detected. Root Cause Node: AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement, Target Node: PetSite, Affected Metric: availability_Average. Path: ['PetSite', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.10, with 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement' identified as the root cause and 'PetSite' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']."
lambdastatusupdater_AWS::Lambda::Function,payforadoption_AWS::ECS::Container,latency,0.057861635,latency_p95,"['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']",1_14,"The path of the issue is from payforadoption_AWS::ECS::Container, through PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage to lambdastatusupdater_AWS::Lambda, to lambdastatusupdater_AWS::Lambda::Function.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.06 was detected. Root Cause Node: payforadoption_AWS::ECS::Container, Target Node: lambdastatusupdater_AWS::Lambda::Function, Affected Metric: latency_p95. Path: ['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.06, with 'payforadoption_AWS::ECS::Container' identified as the root cause and 'lambdastatusupdater_AWS::Lambda::Function' as the target. The affected metric was 'latency_p95'. The path involved: ['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']."
PetSearch_client,PetSearch_AWS::ECS::Fargate,latency,0.1089457,availability_Average,"['PetSearch_client', 'PetSearch_AWS::ECS::Fargate']",2_30,The path of the issue is from PetSearch_client to PetSearch_AWS::ECS::Fargate.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.11 was detected. Root Cause Node: PetSearch_AWS::ECS::Fargate, Target Node: PetSearch_client, Affected Metric: availability_Average. Path: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.11, with 'PetSearch_AWS::ECS::Fargate' identified as the root cause and 'PetSearch_client' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate']."
lambda_step_readDDB,lambda_step_readDDB_AWS::Lambda::Function,latency,0.063621655,latency_p50,"['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']",1_33,The path of the issue is from lambda_step_readDDB_AWS::Lambda::Function to lambda_step_readDDB.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.06 was detected. Root Cause Node: lambda_step_readDDB_AWS::Lambda::Function, Target Node: lambda_step_readDDB, Affected Metric: latency_p50. Path: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.06, with 'lambda_step_readDDB_AWS::Lambda::Function' identified as the root cause and 'lambda_step_readDDB' as the target. The affected metric was 'latency_p50'. The path involved: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']."
PetSite,SimpleSystemsManagement_AWS::SimpleSystemsManagement,latency,0.055479396,availability_Average,"['PetSite', 'SimpleSystemsManagement_AWS::SimpleSystemsManagement']",0_25,The path of the issue is from PetSite to SimpleSystemsManagement_AWS::SimpleSystemsManagement.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.06 was detected. Root Cause Node: SimpleSystemsManagement_AWS::SimpleSystemsManagement, Target Node: PetSite, Affected Metric: availability_Average. Path: ['PetSite', 'SimpleSystemsManagement_AWS::SimpleSystemsManagement']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.06, with 'SimpleSystemsManagement_AWS::SimpleSystemsManagement' identified as the root cause and 'PetSite' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'SimpleSystemsManagement_AWS::SimpleSystemsManagement']."
lambda_step_readDDB_AWS::Lambda::Function,lambda_step_readDDB,latency,0.051418269,availability_Average,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']",1_27,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine to lambda_step_readDDB_AWS::Lambda to lambda_step_readDDB_AWS::Lambda::Function to lambda_step_readDDB, to DynamoDB_AWS::DynamoDB.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.05 was detected. Root Cause Node: lambda_step_readDDB, Target Node: lambda_step_readDDB_AWS::Lambda::Function, Affected Metric: availability_Average. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.05, with 'lambda_step_readDDB' identified as the root cause and 'lambda_step_readDDB_AWS::Lambda::Function' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']."
Evidently_AWS::Evidently,StepFnStateMachine76D362E8-T67Tg48ke8oK_client,latency,0.050158454,latency_Average,"['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55', 'Evidently_AWS::Evidently']",0_43,"The path of the issue is from StepFnStateMachine76D362E8-T67Tg48ke8oK_client, through AWS::StepFunctions::StateMachine to lambda_step_priceLessThan55_AWS::Lambda to lambda_step_priceLessThan55_AWS::Lambda::Function to lambda_step_priceLessThan55, to Evidently_AWS::Evidently.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.05 was detected. Root Cause Node: StepFnStateMachine76D362E8-T67Tg48ke8oK_client, Target Node: Evidently_AWS::Evidently, Affected Metric: latency_Average. Path: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55', 'Evidently_AWS::Evidently']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.05, with 'StepFnStateMachine76D362E8-T67Tg48ke8oK_client' identified as the root cause and 'Evidently_AWS::Evidently' as the target. The affected metric was 'latency_Average'. The path involved: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55', 'Evidently_AWS::Evidently']."
petlistadoptions_client,petlistadoptions_AWS::ECS::Fargate,latency,0.041138177,latency_p99,"['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']",2_37,"The path of the issue is from petlistadoptions_client, through petlistadoptions_AWS::ECS::Fargate to PetSearch_AWS::ECS::Fargate, to 169.254.170.2_remote.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.04 was detected. Root Cause Node: petlistadoptions_AWS::ECS::Fargate, Target Node: petlistadoptions_client, Affected Metric: latency_p99. Path: ['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.04, with 'petlistadoptions_AWS::ECS::Fargate' identified as the root cause and 'petlistadoptions_client' as the target. The affected metric was 'latency_p99'. The path involved: ['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']."
S3_AWS::S3,PetSearch_AWS::ECS::Fargate,latency,0.073718717,latency_p99,"['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'S3_AWS::S3']",1_28,"The path of the issue is from PetSearch_client, through PetSearch_AWS::ECS::Fargate, to S3_AWS::S3.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.07 was detected. Root Cause Node: PetSearch_AWS::ECS::Fargate, Target Node: S3_AWS::S3, Affected Metric: latency_p99. Path: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'S3_AWS::S3']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.07, with 'PetSearch_AWS::ECS::Fargate' identified as the root cause and 'S3_AWS::S3' as the target. The affected metric was 'latency_p99'. The path involved: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'S3_AWS::S3']."
PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage,lambdastatusupdater_AWS::Lambda,latency,0.091943439,availability_Average,"['PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda']",0_16,The path of the issue is from PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage to lambdastatusupdater_AWS::Lambda.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.09 was detected. Root Cause Node: lambdastatusupdater_AWS::Lambda, Target Node: PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage, Affected Metric: availability_Average. Path: ['PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.09, with 'lambdastatusupdater_AWS::Lambda' identified as the root cause and 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage' as the target. The affected metric was 'availability_Average'. The path involved: ['PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda']."
169.254.170.2_remote,petlistadoptions_AWS::ECS::Fargate,latency,0.078711435,latency_p50,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']",2_49,"The path of the issue is from PetSite, through petlistadoptions_AWS::ECS::Fargate to PetSearch_AWS::ECS::Fargate, to 169.254.170.2_remote.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.08 was detected. Root Cause Node: petlistadoptions_AWS::ECS::Fargate, Target Node: 169.254.170.2_remote, Affected Metric: latency_p50. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.08, with 'petlistadoptions_AWS::ECS::Fargate' identified as the root cause and '169.254.170.2_remote' as the target. The affected metric was 'latency_p50'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']."
payforadoption_AWS::ECS::Container,amazon.com_remote,latency,0.12644677,latency_p90,"['payforadoption_AWS::ECS::Container', 'amazon.com_remote']",1_21,The path of the issue is from payforadoption_AWS::ECS::Container to amazon.com_remote.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.13 was detected. Root Cause Node: amazon.com_remote, Target Node: payforadoption_AWS::ECS::Container, Affected Metric: latency_p90. Path: ['payforadoption_AWS::ECS::Container', 'amazon.com_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.13, with 'amazon.com_remote' identified as the root cause and 'payforadoption_AWS::ECS::Container' as the target. The affected metric was 'latency_p90'. The path involved: ['payforadoption_AWS::ECS::Container', 'amazon.com_remote']."
PetSite,PetSearch_AWS::ECS::Fargate,latency,0.050333149,latency_Average,"['PetSite', 'PetSearch_AWS::ECS::Fargate']",0_40,The path of the issue is from PetSite to PetSearch_AWS::ECS::Fargate.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.05 was detected. Root Cause Node: PetSearch_AWS::ECS::Fargate, Target Node: PetSite, Affected Metric: latency_Average. Path: ['PetSite', 'PetSearch_AWS::ECS::Fargate']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.05, with 'PetSearch_AWS::ECS::Fargate' identified as the root cause and 'PetSite' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSite', 'PetSearch_AWS::ECS::Fargate']."
AWS::StepFunctions::StateMachine,StepFnStateMachine76D362E8-T67Tg48ke8oK_client,latency,0.040083891,latency_p99,"['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function']",2_15,"The path of the issue is from StepFnStateMachine76D362E8-T67Tg48ke8oK_client, through AWS::StepFunctions::StateMachine to lambda_step_readDDB_AWS::Lambda, to lambda_step_readDDB_AWS::Lambda::Function.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.04 was detected. Root Cause Node: StepFnStateMachine76D362E8-T67Tg48ke8oK_client, Target Node: AWS::StepFunctions::StateMachine, Affected Metric: latency_p99. Path: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.04, with 'StepFnStateMachine76D362E8-T67Tg48ke8oK_client' identified as the root cause and 'AWS::StepFunctions::StateMachine' as the target. The affected metric was 'latency_p99'. The path involved: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function']."
PetSite,AWS::StepFunctions::StateMachine,latency,0.069288316,latency_p90,"['PetSite', 'AWS::StepFunctions::StateMachine']",2_9,The path of the issue is from PetSite to AWS::StepFunctions::StateMachine.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.07 was detected. Root Cause Node: AWS::StepFunctions::StateMachine, Target Node: PetSite, Affected Metric: latency_p90. Path: ['PetSite', 'AWS::StepFunctions::StateMachine']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.07, with 'AWS::StepFunctions::StateMachine' identified as the root cause and 'PetSite' as the target. The affected metric was 'latency_p90'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine']."
PetSearch_AWS::ECS::Fargate,PetSearch_client,latency,0.042730043,latency_p99,"['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']",1_31,"The path of the issue is from PetSearch_client, through PetSearch_AWS::ECS::Fargate, to petInfo_AWS::DynamoDB::Table.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.04 was detected. Root Cause Node: PetSearch_client, Target Node: PetSearch_AWS::ECS::Fargate, Affected Metric: latency_p99. Path: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.04, with 'PetSearch_client' identified as the root cause and 'PetSearch_AWS::ECS::Fargate' as the target. The affected metric was 'latency_p99'. The path involved: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']."
PetSearch_AWS::ECS::Fargate,PetSearch_client,latency,0.120297232,latency_Average,"['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']",0_42,"The path of the issue is from PetSearch_client, through PetSearch_AWS::ECS::Fargate, to petInfo_AWS::DynamoDB::Table.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.12 was detected. Root Cause Node: PetSearch_client, Target Node: PetSearch_AWS::ECS::Fargate, Affected Metric: latency_Average. Path: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.12, with 'PetSearch_client' identified as the root cause and 'PetSearch_AWS::ECS::Fargate' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']."
petInfo_AWS::DynamoDB::Table,lambdastatusupdater_AWS::Lambda::Function,latency,0.068758571,latency_p99,"['lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']",2_16,The path of the issue is from lambdastatusupdater_AWS::Lambda::Function to petInfo_AWS::DynamoDB::Table.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.07 was detected. Root Cause Node: lambdastatusupdater_AWS::Lambda::Function, Target Node: petInfo_AWS::DynamoDB::Table, Affected Metric: latency_p99. Path: ['lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.07, with 'lambdastatusupdater_AWS::Lambda::Function' identified as the root cause and 'petInfo_AWS::DynamoDB::Table' as the target. The affected metric was 'latency_p99'. The path involved: ['lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']."
AWS::StepFunctions::StateMachine,PetSite,latency,0.109575808,availability_Average,"['PetSite', 'AWS::StepFunctions::StateMachine']",2_10,The path of the issue is from PetSite to AWS::StepFunctions::StateMachine.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.11 was detected. Root Cause Node: PetSite, Target Node: AWS::StepFunctions::StateMachine, Affected Metric: availability_Average. Path: ['PetSite', 'AWS::StepFunctions::StateMachine']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.11, with 'PetSite' identified as the root cause and 'AWS::StepFunctions::StateMachine' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine']."
lambda_step_priceGreaterThan55_AWS::Lambda,AWS::StepFunctions::StateMachine,latency,0.099965536,latency_p90,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']",1_43,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine, to lambda_step_priceGreaterThan55_AWS::Lambda.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.10 was detected. Root Cause Node: AWS::StepFunctions::StateMachine, Target Node: lambda_step_priceGreaterThan55_AWS::Lambda, Affected Metric: latency_p90. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.10, with 'AWS::StepFunctions::StateMachine' identified as the root cause and 'lambda_step_priceGreaterThan55_AWS::Lambda' as the target. The affected metric was 'latency_p90'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']."
PetSite,SimpleNotificationService_AWS::SimpleNotificationService,latency,0.123486804,availability_Average,"['PetSite', 'SimpleNotificationService_AWS::SimpleNotificationService']",1_8,The path of the issue is from PetSite to SimpleNotificationService_AWS::SimpleNotificationService.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.12 was detected. Root Cause Node: SimpleNotificationService_AWS::SimpleNotificationService, Target Node: PetSite, Affected Metric: availability_Average. Path: ['PetSite', 'SimpleNotificationService_AWS::SimpleNotificationService']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.12, with 'SimpleNotificationService_AWS::SimpleNotificationService' identified as the root cause and 'PetSite' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'SimpleNotificationService_AWS::SimpleNotificationService']."
lambdastatusupdater_AWS::Lambda::Function,invalid_AWS::DynamoDB::Table,latency,0.110943337,latency_p99,"['lambdastatusupdater_AWS::Lambda::Function', 'invalid_AWS::DynamoDB::Table']",2_44,The path of the issue is from lambdastatusupdater_AWS::Lambda::Function to invalid_AWS::DynamoDB::Table.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.11 was detected. Root Cause Node: invalid_AWS::DynamoDB::Table, Target Node: lambdastatusupdater_AWS::Lambda::Function, Affected Metric: latency_p99. Path: ['lambdastatusupdater_AWS::Lambda::Function', 'invalid_AWS::DynamoDB::Table']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.11, with 'invalid_AWS::DynamoDB::Table' identified as the root cause and 'lambdastatusupdater_AWS::Lambda::Function' as the target. The affected metric was 'latency_p99'. The path involved: ['lambdastatusupdater_AWS::Lambda::Function', 'invalid_AWS::DynamoDB::Table']."
PetSearch_client,PetSearch_AWS::ECS::Fargate,latency,0.041660541,latency_p95,"['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']",0_6,"The path of the issue is from PetSearch_client, through PetSearch_AWS::ECS::Fargate, to 169.254.170.2_remote.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.04 was detected. Root Cause Node: PetSearch_AWS::ECS::Fargate, Target Node: PetSearch_client, Affected Metric: latency_p95. Path: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.04, with 'PetSearch_AWS::ECS::Fargate' identified as the root cause and 'PetSearch_client' as the target. The affected metric was 'latency_p95'. The path involved: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']."
PetSearch_AWS::ECS::Fargate,petlistadoptions_AWS::ECS::Fargate,latency,0.080154639,latency_p99,"['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate']",0_2,The path of the issue is from petlistadoptions_AWS::ECS::Fargate to PetSearch_AWS::ECS::Fargate.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.08 was detected. Root Cause Node: petlistadoptions_AWS::ECS::Fargate, Target Node: PetSearch_AWS::ECS::Fargate, Affected Metric: latency_p99. Path: ['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.08, with 'petlistadoptions_AWS::ECS::Fargate' identified as the root cause and 'PetSearch_AWS::ECS::Fargate' as the target. The affected metric was 'latency_p99'. The path involved: ['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate']."
PetSearch_AWS::ECS::Fargate,petInfo_AWS::DynamoDB::Table,latency,0.119255293,latency_Average,"['PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']",1_30,The path of the issue is from PetSearch_AWS::ECS::Fargate to petInfo_AWS::DynamoDB::Table.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.12 was detected. Root Cause Node: petInfo_AWS::DynamoDB::Table, Target Node: PetSearch_AWS::ECS::Fargate, Affected Metric: latency_Average. Path: ['PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.12, with 'petInfo_AWS::DynamoDB::Table' identified as the root cause and 'PetSearch_AWS::ECS::Fargate' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']."
PetSite,lambda_step_readDDB_AWS::Lambda,latency,0.104625487,latency_Average,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda']",2_40,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine, to lambda_step_readDDB_AWS::Lambda.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.10 was detected. Root Cause Node: lambda_step_readDDB_AWS::Lambda, Target Node: PetSite, Affected Metric: latency_Average. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.10, with 'lambda_step_readDDB_AWS::Lambda' identified as the root cause and 'PetSite' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda']."
PetSite,lambda_step_priceLessThan55_AWS::Lambda,latency,0.074080786,availability_Average,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda']",0_5,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine, to lambda_step_priceLessThan55_AWS::Lambda.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.07 was detected. Root Cause Node: lambda_step_priceLessThan55_AWS::Lambda, Target Node: PetSite, Affected Metric: availability_Average. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.07, with 'lambda_step_priceLessThan55_AWS::Lambda' identified as the root cause and 'PetSite' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda']."
lambdastatusupdater_AWS::Lambda::Function,lambdastatusupdater_AWS::Lambda,latency,0.083424079,latency_p99,"['PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']",0_41,"The path of the issue is from PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage, through lambdastatusupdater_AWS::Lambda, to lambdastatusupdater_AWS::Lambda::Function.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.08 was detected. Root Cause Node: lambdastatusupdater_AWS::Lambda, Target Node: lambdastatusupdater_AWS::Lambda::Function, Affected Metric: latency_p99. Path: ['PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.08, with 'lambdastatusupdater_AWS::Lambda' identified as the root cause and 'lambdastatusupdater_AWS::Lambda::Function' as the target. The affected metric was 'latency_p99'. The path involved: ['PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']."
AWS::StepFunctions::StateMachine,StepFnStateMachine76D362E8-T67Tg48ke8oK_client,latency,0.097109598,latency_p99,"['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda']",0_3,"The path of the issue is from StepFnStateMachine76D362E8-T67Tg48ke8oK_client, through AWS::StepFunctions::StateMachine, to lambda_step_priceLessThan55_AWS::Lambda.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.10 was detected. Root Cause Node: StepFnStateMachine76D362E8-T67Tg48ke8oK_client, Target Node: AWS::StepFunctions::StateMachine, Affected Metric: latency_p99. Path: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.10, with 'StepFnStateMachine76D362E8-T67Tg48ke8oK_client' identified as the root cause and 'AWS::StepFunctions::StateMachine' as the target. The affected metric was 'latency_p99'. The path involved: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda']."
lambda_step_readDDB_AWS::Lambda,AWS::StepFunctions::StateMachine,latency,0.065588863,latency_p50,"['AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']",2_38,"The path of the issue is from AWS::StepFunctions::StateMachine, through lambda_step_readDDB_AWS::Lambda to lambda_step_readDDB_AWS::Lambda::Function, to lambda_step_readDDB.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.07 was detected. Root Cause Node: AWS::StepFunctions::StateMachine, Target Node: lambda_step_readDDB_AWS::Lambda, Affected Metric: latency_p50. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.07, with 'AWS::StepFunctions::StateMachine' identified as the root cause and 'lambda_step_readDDB_AWS::Lambda' as the target. The affected metric was 'latency_p50'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']."
petlistadoptions_AWS::ECS::Fargate,PetSite,latency,0.119715841,latency_p95,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']",2_17,"The path of the issue is from PetSite, through petlistadoptions_AWS::ECS::Fargate to PetSearch_AWS::ECS::Fargate, to 169.254.170.2_remote.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.12 was detected. Root Cause Node: PetSite, Target Node: petlistadoptions_AWS::ECS::Fargate, Affected Metric: latency_p95. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.12, with 'PetSite' identified as the root cause and 'petlistadoptions_AWS::ECS::Fargate' as the target. The affected metric was 'latency_p95'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']."
lambda_step_readDDB_AWS::Lambda,DynamoDB_AWS::DynamoDB,latency,0.096131058,latency_p99,"['lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']",0_20,"The path of the issue is from lambda_step_readDDB_AWS::Lambda, through lambda_step_readDDB_AWS::Lambda::Function to lambda_step_readDDB, to DynamoDB_AWS::DynamoDB.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.10 was detected. Root Cause Node: DynamoDB_AWS::DynamoDB, Target Node: lambda_step_readDDB_AWS::Lambda, Affected Metric: latency_p99. Path: ['lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.10, with 'DynamoDB_AWS::DynamoDB' identified as the root cause and 'lambda_step_readDDB_AWS::Lambda' as the target. The affected metric was 'latency_p99'. The path involved: ['lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']."
execute-api.us-west-2.amazonaws.com_remote,payforadoption_AWS::ECS::Container,latency,0.034067252,latency_p90,"['payforadoption_AWS::ECS::Container', 'execute-api.us-west-2.amazonaws.com_remote']",1_17,The path of the issue is from payforadoption_AWS::ECS::Container to execute-api.us-west-2.amazonaws.com_remote.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.03 was detected. Root Cause Node: payforadoption_AWS::ECS::Container, Target Node: execute-api.us-west-2.amazonaws.com_remote, Affected Metric: latency_p90. Path: ['payforadoption_AWS::ECS::Container', 'execute-api.us-west-2.amazonaws.com_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.03, with 'payforadoption_AWS::ECS::Container' identified as the root cause and 'execute-api.us-west-2.amazonaws.com_remote' as the target. The affected metric was 'latency_p90'. The path involved: ['payforadoption_AWS::ECS::Container', 'execute-api.us-west-2.amazonaws.com_remote']."
lambda_step_readDDB_AWS::Lambda::Function,DynamoDB_AWS::DynamoDB,latency,0.11793618,latency_p50,"['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']",0_18,"The path of the issue is from lambda_step_readDDB_AWS::Lambda::Function, through lambda_step_readDDB, to DynamoDB_AWS::DynamoDB.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.12 was detected. Root Cause Node: DynamoDB_AWS::DynamoDB, Target Node: lambda_step_readDDB_AWS::Lambda::Function, Affected Metric: latency_p50. Path: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.12, with 'DynamoDB_AWS::DynamoDB' identified as the root cause and 'lambda_step_readDDB_AWS::Lambda::Function' as the target. The affected metric was 'latency_p50'. The path involved: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']."
AWS::StepFunctions::StateMachine,lambda_step_priceGreaterThan55_AWS::Lambda,latency,0.070515163,availability_Average,"['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']",2_12,The path of the issue is from AWS::StepFunctions::StateMachine to lambda_step_priceGreaterThan55_AWS::Lambda.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.07 was detected. Root Cause Node: lambda_step_priceGreaterThan55_AWS::Lambda, Target Node: AWS::StepFunctions::StateMachine, Affected Metric: availability_Average. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.07, with 'lambda_step_priceGreaterThan55_AWS::Lambda' identified as the root cause and 'AWS::StepFunctions::StateMachine' as the target. The affected metric was 'availability_Average'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']."
AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement,PetSearch_AWS::ECS::Fargate,latency,0.039219077,latency_p95,"['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']",1_40,"The path of the issue is from petlistadoptions_AWS::ECS::Fargate, through PetSearch_AWS::ECS::Fargate, to AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.04 was detected. Root Cause Node: PetSearch_AWS::ECS::Fargate, Target Node: AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement, Affected Metric: latency_p95. Path: ['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.04, with 'PetSearch_AWS::ECS::Fargate' identified as the root cause and 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement' as the target. The affected metric was 'latency_p95'. The path involved: ['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']."
lambdastatusupdater_AWS::Lambda::Function,lambdastatusupdater_AWS::Lambda,latency,0.034218047,latency_p90,"['lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']",2_39,The path of the issue is from lambdastatusupdater_AWS::Lambda to lambdastatusupdater_AWS::Lambda::Function.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.03 was detected. Root Cause Node: lambdastatusupdater_AWS::Lambda, Target Node: lambdastatusupdater_AWS::Lambda::Function, Affected Metric: latency_p90. Path: ['lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.03, with 'lambdastatusupdater_AWS::Lambda' identified as the root cause and 'lambdastatusupdater_AWS::Lambda::Function' as the target. The affected metric was 'latency_p90'. The path involved: ['lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']."
169.254.170.2_remote,PetSearch_AWS::ECS::Fargate,latency,0.091498772,latency_p95,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']",1_24,"The path of the issue is from PetSite, through petlistadoptions_AWS::ECS::Fargate to PetSearch_AWS::ECS::Fargate, to 169.254.170.2_remote.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.09 was detected. Root Cause Node: PetSearch_AWS::ECS::Fargate, Target Node: 169.254.170.2_remote, Affected Metric: latency_p95. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.09, with 'PetSearch_AWS::ECS::Fargate' identified as the root cause and '169.254.170.2_remote' as the target. The affected metric was 'latency_p95'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']."
lambda_step_priceLessThan55,lambda_step_priceLessThan55_AWS::Lambda::Function,latency,0.121364614,latency_p50,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55']",2_41,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine to lambda_step_priceLessThan55_AWS::Lambda to lambda_step_priceLessThan55_AWS::Lambda::Function, to lambda_step_priceLessThan55.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.12 was detected. Root Cause Node: lambda_step_priceLessThan55_AWS::Lambda::Function, Target Node: lambda_step_priceLessThan55, Affected Metric: latency_p50. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.12, with 'lambda_step_priceLessThan55_AWS::Lambda::Function' identified as the root cause and 'lambda_step_priceLessThan55' as the target. The affected metric was 'latency_p50'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55']."
AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement,petlistadoptions_AWS::ECS::Fargate,latency,0.09461717,latency_p99,"['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']",1_19,"The path of the issue is from petlistadoptions_client, through petlistadoptions_AWS::ECS::Fargate to PetSearch_AWS::ECS::Fargate, to AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.09 was detected. Root Cause Node: petlistadoptions_AWS::ECS::Fargate, Target Node: AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement, Affected Metric: latency_p99. Path: ['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.09, with 'petlistadoptions_AWS::ECS::Fargate' identified as the root cause and 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement' as the target. The affected metric was 'latency_p99'. The path involved: ['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']."
lambda_step_priceLessThan55_AWS::Lambda,lambda_step_priceLessThan55_AWS::Lambda::Function,latency,0.121670018,latency_Average,"['AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']",1_9,"The path of the issue is from AWS::StepFunctions::StateMachine, through lambda_step_priceLessThan55_AWS::Lambda, to lambda_step_priceLessThan55_AWS::Lambda::Function.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.12 was detected. Root Cause Node: lambda_step_priceLessThan55_AWS::Lambda::Function, Target Node: lambda_step_priceLessThan55_AWS::Lambda, Affected Metric: latency_Average. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.12, with 'lambda_step_priceLessThan55_AWS::Lambda::Function' identified as the root cause and 'lambda_step_priceLessThan55_AWS::Lambda' as the target. The affected metric was 'latency_Average'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']."
PGSQL Query_remote,PetSite,latency,0.082132836,latency_Average,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PGSQL Query_remote']",1_47,"The path of the issue is from PetSite, through petlistadoptions_AWS::ECS::Fargate, to PGSQL Query_remote.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.08 was detected. Root Cause Node: PetSite, Target Node: PGSQL Query_remote, Affected Metric: latency_Average. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PGSQL Query_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.08, with 'PetSite' identified as the root cause and 'PGSQL Query_remote' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PGSQL Query_remote']."
lambda_step_readDDB,lambda_step_readDDB_AWS::Lambda,latency,0.10751138,availability_Average,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']",0_24,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine to lambda_step_readDDB_AWS::Lambda to lambda_step_readDDB_AWS::Lambda::Function, to lambda_step_readDDB.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.11 was detected. Root Cause Node: lambda_step_readDDB_AWS::Lambda, Target Node: lambda_step_readDDB, Affected Metric: availability_Average. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.11, with 'lambda_step_readDDB_AWS::Lambda' identified as the root cause and 'lambda_step_readDDB' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']."
lambdastatusupdater_AWS::Lambda,payforadoption_AWS::ECS::Container,latency,0.070184069,latency_p50,"['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda']",0_33,"The path of the issue is from payforadoption_AWS::ECS::Container, through PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage, to lambdastatusupdater_AWS::Lambda.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.07 was detected. Root Cause Node: payforadoption_AWS::ECS::Container, Target Node: lambdastatusupdater_AWS::Lambda, Affected Metric: latency_p50. Path: ['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.07, with 'payforadoption_AWS::ECS::Container' identified as the root cause and 'lambdastatusupdater_AWS::Lambda' as the target. The affected metric was 'latency_p50'. The path involved: ['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda']."
lambda_step_priceGreaterThan55,Evidently_AWS::Evidently,latency,0.085187166,latency_p95,"['lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']",1_42,The path of the issue is from lambda_step_priceGreaterThan55 to Evidently_AWS::Evidently.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.09 was detected. Root Cause Node: Evidently_AWS::Evidently, Target Node: lambda_step_priceGreaterThan55, Affected Metric: latency_p95. Path: ['lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.09, with 'Evidently_AWS::Evidently' identified as the root cause and 'lambda_step_priceGreaterThan55' as the target. The affected metric was 'latency_p95'. The path involved: ['lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']."
lambda_step_priceGreaterThan55,lambda_step_priceGreaterThan55_AWS::Lambda,latency,0.121540479,latency_p50,"['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55']",0_11,"The path of the issue is from StepFnStateMachine76D362E8-T67Tg48ke8oK_client, through AWS::StepFunctions::StateMachine to lambda_step_priceGreaterThan55_AWS::Lambda to lambda_step_priceGreaterThan55_AWS::Lambda::Function, to lambda_step_priceGreaterThan55.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.12 was detected. Root Cause Node: lambda_step_priceGreaterThan55_AWS::Lambda, Target Node: lambda_step_priceGreaterThan55, Affected Metric: latency_p50. Path: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.12, with 'lambda_step_priceGreaterThan55_AWS::Lambda' identified as the root cause and 'lambda_step_priceGreaterThan55' as the target. The affected metric was 'latency_p50'. The path involved: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55']."
SimpleNotificationService_AWS::SimpleNotificationService,PetSite,latency,0.094947362,latency_p50,"['PetSite', 'SimpleNotificationService_AWS::SimpleNotificationService']",2_14,The path of the issue is from PetSite to SimpleNotificationService_AWS::SimpleNotificationService.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.09 was detected. Root Cause Node: PetSite, Target Node: SimpleNotificationService_AWS::SimpleNotificationService, Affected Metric: latency_p50. Path: ['PetSite', 'SimpleNotificationService_AWS::SimpleNotificationService']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.09, with 'PetSite' identified as the root cause and 'SimpleNotificationService_AWS::SimpleNotificationService' as the target. The affected metric was 'latency_p50'. The path involved: ['PetSite', 'SimpleNotificationService_AWS::SimpleNotificationService']."
AWS::StepFunctions::StateMachine,lambda_step_readDDB_AWS::Lambda,latency,0.083213425,latency_p90,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda']",0_17,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine, to lambda_step_readDDB_AWS::Lambda.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.08 was detected. Root Cause Node: lambda_step_readDDB_AWS::Lambda, Target Node: AWS::StepFunctions::StateMachine, Affected Metric: latency_p90. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.08, with 'lambda_step_readDDB_AWS::Lambda' identified as the root cause and 'AWS::StepFunctions::StateMachine' as the target. The affected metric was 'latency_p90'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda']."
lambda_step_priceGreaterThan55_AWS::Lambda,AWS::StepFunctions::StateMachine,latency,0.055943205,latency_p50,"['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']",0_28,"The path of the issue is from AWS::StepFunctions::StateMachine, through lambda_step_priceGreaterThan55_AWS::Lambda to lambda_step_priceGreaterThan55_AWS::Lambda::Function to lambda_step_priceGreaterThan55, to Evidently_AWS::Evidently.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.06 was detected. Root Cause Node: AWS::StepFunctions::StateMachine, Target Node: lambda_step_priceGreaterThan55_AWS::Lambda, Affected Metric: latency_p50. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.06, with 'AWS::StepFunctions::StateMachine' identified as the root cause and 'lambda_step_priceGreaterThan55_AWS::Lambda' as the target. The affected metric was 'latency_p50'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']."
petlistadoptions_AWS::ECS::Fargate,petInfo_AWS::DynamoDB::Table,latency,0.065924132,availability_Average,"['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']",2_4,"The path of the issue is from petlistadoptions_AWS::ECS::Fargate, through PetSearch_AWS::ECS::Fargate, to petInfo_AWS::DynamoDB::Table.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.07 was detected. Root Cause Node: petInfo_AWS::DynamoDB::Table, Target Node: petlistadoptions_AWS::ECS::Fargate, Affected Metric: availability_Average. Path: ['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.07, with 'petInfo_AWS::DynamoDB::Table' identified as the root cause and 'petlistadoptions_AWS::ECS::Fargate' as the target. The affected metric was 'availability_Average'. The path involved: ['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']."
lambdastatusupdater_AWS::Lambda::Function,petInfo_AWS::DynamoDB::Table,latency,0.036039326,latency_p50,"['lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']",0_0,The path of the issue is from lambdastatusupdater_AWS::Lambda::Function to petInfo_AWS::DynamoDB::Table.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.04 was detected. Root Cause Node: petInfo_AWS::DynamoDB::Table, Target Node: lambdastatusupdater_AWS::Lambda::Function, Affected Metric: latency_p50. Path: ['lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.04, with 'petInfo_AWS::DynamoDB::Table' identified as the root cause and 'lambdastatusupdater_AWS::Lambda::Function' as the target. The affected metric was 'latency_p50'. The path involved: ['lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']."
payforadoption_AWS::ECS::Container,adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL,latency,0.058135487,latency_p50,"['payforadoption_AWS::ECS::Container', 'adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL']",0_23,The path of the issue is from payforadoption_AWS::ECS::Container to adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.06 was detected. Root Cause Node: adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL, Target Node: payforadoption_AWS::ECS::Container, Affected Metric: latency_p50. Path: ['payforadoption_AWS::ECS::Container', 'adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.06, with 'adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL' identified as the root cause and 'payforadoption_AWS::ECS::Container' as the target. The affected metric was 'latency_p50'. The path involved: ['payforadoption_AWS::ECS::Container', 'adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL']."
Servi-searc.us-west-2.elb.amazonaws.com_remote,petlistadoptions_AWS::ECS::Fargate,latency,0.086717001,latency_p99,"['petlistadoptions_AWS::ECS::Fargate', 'Servi-searc.us-west-2.elb.amazonaws.com_remote']",0_45,The path of the issue is from petlistadoptions_AWS::ECS::Fargate to Servi-searc.us-west-2.elb.amazonaws.com_remote.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.09 was detected. Root Cause Node: petlistadoptions_AWS::ECS::Fargate, Target Node: Servi-searc.us-west-2.elb.amazonaws.com_remote, Affected Metric: latency_p99. Path: ['petlistadoptions_AWS::ECS::Fargate', 'Servi-searc.us-west-2.elb.amazonaws.com_remote']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.09, with 'petlistadoptions_AWS::ECS::Fargate' identified as the root cause and 'Servi-searc.us-west-2.elb.amazonaws.com_remote' as the target. The affected metric was 'latency_p99'. The path involved: ['petlistadoptions_AWS::ECS::Fargate', 'Servi-searc.us-west-2.elb.amazonaws.com_remote']."
AWS::StepFunctions::StateMachine,lambda_step_priceLessThan55_AWS::Lambda,latency,0.031525818,latency_p90,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55']",0_7,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine to lambda_step_priceLessThan55_AWS::Lambda to lambda_step_priceLessThan55_AWS::Lambda::Function, to lambda_step_priceLessThan55.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.03 was detected. Root Cause Node: lambda_step_priceLessThan55_AWS::Lambda, Target Node: AWS::StepFunctions::StateMachine, Affected Metric: latency_p90. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.03, with 'lambda_step_priceLessThan55_AWS::Lambda' identified as the root cause and 'AWS::StepFunctions::StateMachine' as the target. The affected metric was 'latency_p90'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55']."
petInfo_AWS::DynamoDB::Table,lambdastatusupdater_AWS::Lambda,latency,0.044543976,latency_p95,"['lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']",0_44,"The path of the issue is from lambdastatusupdater_AWS::Lambda, through lambdastatusupdater_AWS::Lambda::Function, to petInfo_AWS::DynamoDB::Table.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.04 was detected. Root Cause Node: lambdastatusupdater_AWS::Lambda, Target Node: petInfo_AWS::DynamoDB::Table, Affected Metric: latency_p95. Path: ['lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.04, with 'lambdastatusupdater_AWS::Lambda' identified as the root cause and 'petInfo_AWS::DynamoDB::Table' as the target. The affected metric was 'latency_p95'. The path involved: ['lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']."
PetSite,servi-searc.us-west-2.elb.amazonaws.com_remote,latency,0.051952722,latency_p95,"['PetSite', 'servi-searc.us-west-2.elb.amazonaws.com_remote']",1_18,The path of the issue is from PetSite to servi-searc.us-west-2.elb.amazonaws.com_remote.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.05 was detected. Root Cause Node: servi-searc.us-west-2.elb.amazonaws.com_remote, Target Node: PetSite, Affected Metric: latency_p95. Path: ['PetSite', 'servi-searc.us-west-2.elb.amazonaws.com_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.05, with 'servi-searc.us-west-2.elb.amazonaws.com_remote' identified as the root cause and 'PetSite' as the target. The affected metric was 'latency_p95'. The path involved: ['PetSite', 'servi-searc.us-west-2.elb.amazonaws.com_remote']."
invalid_AWS::DynamoDB::Table,payforadoption_AWS::ECS::Container,latency,0.120055467,latency_p50,"['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'invalid_AWS::DynamoDB::Table']",1_38,"The path of the issue is from payforadoption_AWS::ECS::Container, through PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage to lambdastatusupdater_AWS::Lambda to lambdastatusupdater_AWS::Lambda::Function, to invalid_AWS::DynamoDB::Table.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.12 was detected. Root Cause Node: payforadoption_AWS::ECS::Container, Target Node: invalid_AWS::DynamoDB::Table, Affected Metric: latency_p50. Path: ['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'invalid_AWS::DynamoDB::Table']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.12, with 'payforadoption_AWS::ECS::Container' identified as the root cause and 'invalid_AWS::DynamoDB::Table' as the target. The affected metric was 'latency_p50'. The path involved: ['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'invalid_AWS::DynamoDB::Table']."
AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement,petlistadoptions_AWS::ECS::Fargate,latency,0.094520757,latency_p90,"['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']",1_16,"The path of the issue is from petlistadoptions_client, through petlistadoptions_AWS::ECS::Fargate to PetSearch_AWS::ECS::Fargate, to AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.09 was detected. Root Cause Node: petlistadoptions_AWS::ECS::Fargate, Target Node: AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement, Affected Metric: latency_p90. Path: ['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.09, with 'petlistadoptions_AWS::ECS::Fargate' identified as the root cause and 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement' as the target. The affected metric was 'latency_p90'. The path involved: ['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']."
AWS::StepFunctions::StateMachine,PetSite,latency,0.047682695,availability_Average,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']",0_27,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine, to lambda_step_priceGreaterThan55_AWS::Lambda.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.05 was detected. Root Cause Node: PetSite, Target Node: AWS::StepFunctions::StateMachine, Affected Metric: availability_Average. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.05, with 'PetSite' identified as the root cause and 'AWS::StepFunctions::StateMachine' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']."
SimpleNotificationService_AWS::SimpleNotificationService,PetSite,latency,0.10875513,availability_Average,"['PetSite', 'SimpleNotificationService_AWS::SimpleNotificationService']",0_19,The path of the issue is from PetSite to SimpleNotificationService_AWS::SimpleNotificationService.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.11 was detected. Root Cause Node: PetSite, Target Node: SimpleNotificationService_AWS::SimpleNotificationService, Affected Metric: availability_Average. Path: ['PetSite', 'SimpleNotificationService_AWS::SimpleNotificationService']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.11, with 'PetSite' identified as the root cause and 'SimpleNotificationService_AWS::SimpleNotificationService' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'SimpleNotificationService_AWS::SimpleNotificationService']."
lambda_step_readDDB_AWS::Lambda::Function,lambda_step_readDDB,latency,0.061877853,availability_Average,"['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']",1_39,The path of the issue is from lambda_step_readDDB_AWS::Lambda::Function to lambda_step_readDDB.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.06 was detected. Root Cause Node: lambda_step_readDDB, Target Node: lambda_step_readDDB_AWS::Lambda::Function, Affected Metric: availability_Average. Path: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.06, with 'lambda_step_readDDB' identified as the root cause and 'lambda_step_readDDB_AWS::Lambda::Function' as the target. The affected metric was 'availability_Average'. The path involved: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']."
servi-petsi.us-west-2.elb.amazonaws.com_remote,PetSite,latency,0.10535873,latency_p50,"['PetSite', 'servi-petsi.us-west-2.elb.amazonaws.com_remote']",2_47,The path of the issue is from PetSite to servi-petsi.us-west-2.elb.amazonaws.com_remote.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.11 was detected. Root Cause Node: PetSite, Target Node: servi-petsi.us-west-2.elb.amazonaws.com_remote, Affected Metric: latency_p50. Path: ['PetSite', 'servi-petsi.us-west-2.elb.amazonaws.com_remote']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.11, with 'PetSite' identified as the root cause and 'servi-petsi.us-west-2.elb.amazonaws.com_remote' as the target. The affected metric was 'latency_p50'. The path involved: ['PetSite', 'servi-petsi.us-west-2.elb.amazonaws.com_remote']."
STS_AWS::STS,PetSite,latency,0.097222426,latency_p90,"['PetSite', 'STS_AWS::STS']",1_2,The path of the issue is from PetSite to STS_AWS::STS.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.10 was detected. Root Cause Node: PetSite, Target Node: STS_AWS::STS, Affected Metric: latency_p90. Path: ['PetSite', 'STS_AWS::STS']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.10, with 'PetSite' identified as the root cause and 'STS_AWS::STS' as the target. The affected metric was 'latency_p90'. The path involved: ['PetSite', 'STS_AWS::STS']."
PetSite,DynamoDB_AWS::DynamoDB,latency,0.075993088,latency_Average,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']",2_36,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine to lambda_step_readDDB_AWS::Lambda to lambda_step_readDDB_AWS::Lambda::Function to lambda_step_readDDB, to DynamoDB_AWS::DynamoDB.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.08 was detected. Root Cause Node: DynamoDB_AWS::DynamoDB, Target Node: PetSite, Affected Metric: latency_Average. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.08, with 'DynamoDB_AWS::DynamoDB' identified as the root cause and 'PetSite' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']."
AWS::StepFunctions::StateMachine,lambda_step_priceLessThan55_AWS::Lambda,latency,0.115283203,availability_Average,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda']",0_48,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine, to lambda_step_priceLessThan55_AWS::Lambda.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.12 was detected. Root Cause Node: lambda_step_priceLessThan55_AWS::Lambda, Target Node: AWS::StepFunctions::StateMachine, Affected Metric: availability_Average. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.12, with 'lambda_step_priceLessThan55_AWS::Lambda' identified as the root cause and 'AWS::StepFunctions::StateMachine' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda']."
PetSite,www.amazon.com_remote,latency,0.040082266,latency_Average,"['PetSite', 'payforadoption_AWS::ECS::Container', 'www.amazon.com_remote']",2_22,"The path of the issue is from PetSite, through payforadoption_AWS::ECS::Container, to www.amazon.com_remote.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.04 was detected. Root Cause Node: www.amazon.com_remote, Target Node: PetSite, Affected Metric: latency_Average. Path: ['PetSite', 'payforadoption_AWS::ECS::Container', 'www.amazon.com_remote']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.04, with 'www.amazon.com_remote' identified as the root cause and 'PetSite' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSite', 'payforadoption_AWS::ECS::Container', 'www.amazon.com_remote']."
petInfo_AWS::DynamoDB::Table,PetSearch_client,latency,0.115230519,latency_Average,"['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']",0_35,"The path of the issue is from PetSearch_client, through PetSearch_AWS::ECS::Fargate, to petInfo_AWS::DynamoDB::Table.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.12 was detected. Root Cause Node: PetSearch_client, Target Node: petInfo_AWS::DynamoDB::Table, Affected Metric: latency_Average. Path: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.12, with 'PetSearch_client' identified as the root cause and 'petInfo_AWS::DynamoDB::Table' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', 'petInfo_AWS::DynamoDB::Table']."
lambda_step_readDDB_AWS::Lambda,AWS::StepFunctions::StateMachine,latency,0.076337225,latency_p90,"['AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda']",2_21,The path of the issue is from AWS::StepFunctions::StateMachine to lambda_step_readDDB_AWS::Lambda.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.08 was detected. Root Cause Node: AWS::StepFunctions::StateMachine, Target Node: lambda_step_readDDB_AWS::Lambda, Affected Metric: latency_p90. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.08, with 'AWS::StepFunctions::StateMachine' identified as the root cause and 'lambda_step_readDDB_AWS::Lambda' as the target. The affected metric was 'latency_p90'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda']."
lambdastatusupdater_AWS::Lambda::Function,petInfo_AWS::DynamoDB::Table,latency,0.055445766,latency_p95,"['lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']",1_1,The path of the issue is from lambdastatusupdater_AWS::Lambda::Function to petInfo_AWS::DynamoDB::Table.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.06 was detected. Root Cause Node: petInfo_AWS::DynamoDB::Table, Target Node: lambdastatusupdater_AWS::Lambda::Function, Affected Metric: latency_p95. Path: ['lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.06, with 'petInfo_AWS::DynamoDB::Table' identified as the root cause and 'lambdastatusupdater_AWS::Lambda::Function' as the target. The affected metric was 'latency_p95'. The path involved: ['lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']."
PetSearch_client,169.254.170.2_remote,latency,0.089179984,availability_Average,"['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']",2_18,"The path of the issue is from PetSearch_client, through PetSearch_AWS::ECS::Fargate, to 169.254.170.2_remote.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.09 was detected. Root Cause Node: 169.254.170.2_remote, Target Node: PetSearch_client, Affected Metric: availability_Average. Path: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.09, with '169.254.170.2_remote' identified as the root cause and 'PetSearch_client' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']."
PetSite,lambda_step_priceLessThan55_AWS::Lambda,latency,0.104768587,availability_Average,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']",0_21,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine to lambda_step_priceLessThan55_AWS::Lambda, to lambda_step_priceLessThan55_AWS::Lambda::Function.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.10 was detected. Root Cause Node: lambda_step_priceLessThan55_AWS::Lambda, Target Node: PetSite, Affected Metric: availability_Average. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.10, with 'lambda_step_priceLessThan55_AWS::Lambda' identified as the root cause and 'PetSite' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']."
PetSearch_AWS::ECS::Fargate,petlistadoptions_AWS::ECS::Fargate,latency,0.101824097,availability_Average,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']",0_46,"The path of the issue is from PetSite, through petlistadoptions_AWS::ECS::Fargate to PetSearch_AWS::ECS::Fargate, to 169.254.170.2_remote.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.10 was detected. Root Cause Node: petlistadoptions_AWS::ECS::Fargate, Target Node: PetSearch_AWS::ECS::Fargate, Affected Metric: availability_Average. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.10, with 'petlistadoptions_AWS::ECS::Fargate' identified as the root cause and 'PetSearch_AWS::ECS::Fargate' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']."
lambda_step_readDDB_AWS::Lambda::Function,StepFnStateMachine76D362E8-T67Tg48ke8oK_client,latency,0.093556343,latency_p95,"['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'SSM_AWS::SSM']",2_23,"The path of the issue is from StepFnStateMachine76D362E8-T67Tg48ke8oK_client, through AWS::StepFunctions::StateMachine to lambda_step_readDDB_AWS::Lambda to lambda_step_readDDB_AWS::Lambda::Function to lambda_step_readDDB, to SSM_AWS::SSM.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.09 was detected. Root Cause Node: StepFnStateMachine76D362E8-T67Tg48ke8oK_client, Target Node: lambda_step_readDDB_AWS::Lambda::Function, Affected Metric: latency_p95. Path: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'SSM_AWS::SSM']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.09, with 'StepFnStateMachine76D362E8-T67Tg48ke8oK_client' identified as the root cause and 'lambda_step_readDDB_AWS::Lambda::Function' as the target. The affected metric was 'latency_p95'. The path involved: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'SSM_AWS::SSM']."
petlistadoptions_AWS::ECS::Fargate,AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement,latency,0.030726956,latency_p99,"['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']",1_13,"The path of the issue is from petlistadoptions_AWS::ECS::Fargate, through PetSearch_AWS::ECS::Fargate, to AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.03 was detected. Root Cause Node: AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement, Target Node: petlistadoptions_AWS::ECS::Fargate, Affected Metric: latency_p99. Path: ['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.03, with 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement' identified as the root cause and 'petlistadoptions_AWS::ECS::Fargate' as the target. The affected metric was 'latency_p99'. The path involved: ['petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']."
SimpleSystemsManagement_AWS::SimpleSystemsManagement,PetSite,latency,0.068374992,availability_Average,"['PetSite', 'SimpleSystemsManagement_AWS::SimpleSystemsManagement']",2_45,The path of the issue is from PetSite to SimpleSystemsManagement_AWS::SimpleSystemsManagement.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.07 was detected. Root Cause Node: PetSite, Target Node: SimpleSystemsManagement_AWS::SimpleSystemsManagement, Affected Metric: availability_Average. Path: ['PetSite', 'SimpleSystemsManagement_AWS::SimpleSystemsManagement']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.07, with 'PetSite' identified as the root cause and 'SimpleSystemsManagement_AWS::SimpleSystemsManagement' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'SimpleSystemsManagement_AWS::SimpleSystemsManagement']."
AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement,PetSearch_AWS::ECS::Fargate,latency,0.103660612,latency_p99,"['PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']",2_25,The path of the issue is from PetSearch_AWS::ECS::Fargate to AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.10 was detected. Root Cause Node: PetSearch_AWS::ECS::Fargate, Target Node: AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement, Affected Metric: latency_p99. Path: ['PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.10, with 'PetSearch_AWS::ECS::Fargate' identified as the root cause and 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement' as the target. The affected metric was 'latency_p99'. The path involved: ['PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']."
payforadoption_AWS::ECS::Container,amazon.com_remote,latency,0.053205129,availability_Average,"['PetSite', 'payforadoption_AWS::ECS::Container', 'amazon.com_remote']",1_20,"The path of the issue is from PetSite, through payforadoption_AWS::ECS::Container, to amazon.com_remote.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.05 was detected. Root Cause Node: amazon.com_remote, Target Node: payforadoption_AWS::ECS::Container, Affected Metric: availability_Average. Path: ['PetSite', 'payforadoption_AWS::ECS::Container', 'amazon.com_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.05, with 'amazon.com_remote' identified as the root cause and 'payforadoption_AWS::ECS::Container' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'payforadoption_AWS::ECS::Container', 'amazon.com_remote']."
www.amazon.com_remote,payforadoption_AWS::ECS::Container,latency,0.052194039,availability_Average,"['payforadoption_AWS::ECS::Container', 'www.amazon.com_remote']",2_32,The path of the issue is from payforadoption_AWS::ECS::Container to www.amazon.com_remote.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.05 was detected. Root Cause Node: payforadoption_AWS::ECS::Container, Target Node: www.amazon.com_remote, Affected Metric: availability_Average. Path: ['payforadoption_AWS::ECS::Container', 'www.amazon.com_remote']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.05, with 'payforadoption_AWS::ECS::Container' identified as the root cause and 'www.amazon.com_remote' as the target. The affected metric was 'availability_Average'. The path involved: ['payforadoption_AWS::ECS::Container', 'www.amazon.com_remote']."
payforadoption_AWS::ECS::Container,execute-api.us-west-2.amazonaws.com_remote,latency,0.10356793,latency_p90,"['payforadoption_AWS::ECS::Container', 'execute-api.us-west-2.amazonaws.com_remote']",1_12,The path of the issue is from payforadoption_AWS::ECS::Container to execute-api.us-west-2.amazonaws.com_remote.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.10 was detected. Root Cause Node: execute-api.us-west-2.amazonaws.com_remote, Target Node: payforadoption_AWS::ECS::Container, Affected Metric: latency_p90. Path: ['payforadoption_AWS::ECS::Container', 'execute-api.us-west-2.amazonaws.com_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.10, with 'execute-api.us-west-2.amazonaws.com_remote' identified as the root cause and 'payforadoption_AWS::ECS::Container' as the target. The affected metric was 'latency_p90'. The path involved: ['payforadoption_AWS::ECS::Container', 'execute-api.us-west-2.amazonaws.com_remote']."
servi-searc.us-west-2.elb.amazonaws.com_remote,PetSite,latency,0.077860288,latency_p90,"['PetSite', 'servi-searc.us-west-2.elb.amazonaws.com_remote']",2_5,The path of the issue is from PetSite to servi-searc.us-west-2.elb.amazonaws.com_remote.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.08 was detected. Root Cause Node: PetSite, Target Node: servi-searc.us-west-2.elb.amazonaws.com_remote, Affected Metric: latency_p90. Path: ['PetSite', 'servi-searc.us-west-2.elb.amazonaws.com_remote']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.08, with 'PetSite' identified as the root cause and 'servi-searc.us-west-2.elb.amazonaws.com_remote' as the target. The affected metric was 'latency_p90'. The path involved: ['PetSite', 'servi-searc.us-west-2.elb.amazonaws.com_remote']."
PetSearch_AWS::ECS::Fargate,PetSite,latency,0.126915122,latency_p99,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']",0_9,"The path of the issue is from PetSite, through petlistadoptions_AWS::ECS::Fargate to PetSearch_AWS::ECS::Fargate, to AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.13 was detected. Root Cause Node: PetSite, Target Node: PetSearch_AWS::ECS::Fargate, Affected Metric: latency_p99. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.13, with 'PetSite' identified as the root cause and 'PetSearch_AWS::ECS::Fargate' as the target. The affected metric was 'latency_p99'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']."
PetSearch_AWS::ECS::Fargate,PetSite,latency,0.048108539,availability_Average,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate']",2_29,"The path of the issue is from PetSite, through petlistadoptions_AWS::ECS::Fargate, to PetSearch_AWS::ECS::Fargate.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.05 was detected. Root Cause Node: PetSite, Target Node: PetSearch_AWS::ECS::Fargate, Affected Metric: availability_Average. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.05, with 'PetSite' identified as the root cause and 'PetSearch_AWS::ECS::Fargate' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate']."
DynamoDB_AWS::DynamoDB,lambda_step_readDDB_AWS::Lambda::Function,latency,0.091380285,latency_p90,"['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']",1_15,"The path of the issue is from lambda_step_readDDB_AWS::Lambda::Function, through lambda_step_readDDB, to DynamoDB_AWS::DynamoDB.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.09 was detected. Root Cause Node: lambda_step_readDDB_AWS::Lambda::Function, Target Node: DynamoDB_AWS::DynamoDB, Affected Metric: latency_p90. Path: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.09, with 'lambda_step_readDDB_AWS::Lambda::Function' identified as the root cause and 'DynamoDB_AWS::DynamoDB' as the target. The affected metric was 'latency_p90'. The path involved: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']."
lambda_step_priceLessThan55_AWS::Lambda::Function,lambda_step_priceLessThan55_AWS::Lambda,latency,0.113388633,latency_p99,"['lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']",1_5,The path of the issue is from lambda_step_priceLessThan55_AWS::Lambda to lambda_step_priceLessThan55_AWS::Lambda::Function.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.11 was detected. Root Cause Node: lambda_step_priceLessThan55_AWS::Lambda, Target Node: lambda_step_priceLessThan55_AWS::Lambda::Function, Affected Metric: latency_p99. Path: ['lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.11, with 'lambda_step_priceLessThan55_AWS::Lambda' identified as the root cause and 'lambda_step_priceLessThan55_AWS::Lambda::Function' as the target. The affected metric was 'latency_p99'. The path involved: ['lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']."
PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage,lambdastatusupdater_AWS::Lambda::Function,latency,0.104043437,latency_p99,"['PetSite', 'payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']",2_11,"The path of the issue is from PetSite, through payforadoption_AWS::ECS::Container to PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage to lambdastatusupdater_AWS::Lambda, to lambdastatusupdater_AWS::Lambda::Function.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.10 was detected. Root Cause Node: lambdastatusupdater_AWS::Lambda::Function, Target Node: PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage, Affected Metric: latency_p99. Path: ['PetSite', 'payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.10, with 'lambdastatusupdater_AWS::Lambda::Function' identified as the root cause and 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage' as the target. The affected metric was 'latency_p99'. The path involved: ['PetSite', 'payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']."
lambda_step_priceGreaterThan55_AWS::Lambda::Function,AWS::StepFunctions::StateMachine,latency,0.046524412,latency_p99,"['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function']",1_45,"The path of the issue is from AWS::StepFunctions::StateMachine, through lambda_step_priceGreaterThan55_AWS::Lambda, to lambda_step_priceGreaterThan55_AWS::Lambda::Function.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.05 was detected. Root Cause Node: AWS::StepFunctions::StateMachine, Target Node: lambda_step_priceGreaterThan55_AWS::Lambda::Function, Affected Metric: latency_p99. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.05, with 'AWS::StepFunctions::StateMachine' identified as the root cause and 'lambda_step_priceGreaterThan55_AWS::Lambda::Function' as the target. The affected metric was 'latency_p99'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function']."
petlistadoptions_AWS::ECS::Fargate,PGSQL Query_remote,latency,0.119814983,latency_Average,"['petlistadoptions_AWS::ECS::Fargate', 'PGSQL Query_remote']",1_37,The path of the issue is from petlistadoptions_AWS::ECS::Fargate to PGSQL Query_remote.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.12 was detected. Root Cause Node: PGSQL Query_remote, Target Node: petlistadoptions_AWS::ECS::Fargate, Affected Metric: latency_Average. Path: ['petlistadoptions_AWS::ECS::Fargate', 'PGSQL Query_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.12, with 'PGSQL Query_remote' identified as the root cause and 'petlistadoptions_AWS::ECS::Fargate' as the target. The affected metric was 'latency_Average'. The path involved: ['petlistadoptions_AWS::ECS::Fargate', 'PGSQL Query_remote']."
DynamoDB_AWS::DynamoDB,lambda_step_readDDB,latency,0.050884036,latency_p90,"['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']",2_24,"The path of the issue is from lambda_step_readDDB_AWS::Lambda::Function, through lambda_step_readDDB, to DynamoDB_AWS::DynamoDB.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.05 was detected. Root Cause Node: lambda_step_readDDB, Target Node: DynamoDB_AWS::DynamoDB, Affected Metric: latency_p90. Path: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.05, with 'lambda_step_readDDB' identified as the root cause and 'DynamoDB_AWS::DynamoDB' as the target. The affected metric was 'latency_p90'. The path involved: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']."
lambda_step_readDDB_AWS::Lambda::Function,lambda_step_readDDB,latency,0.043707513,latency_p99,"['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']",0_10,The path of the issue is from lambda_step_readDDB_AWS::Lambda::Function to lambda_step_readDDB.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.04 was detected. Root Cause Node: lambda_step_readDDB, Target Node: lambda_step_readDDB_AWS::Lambda::Function, Affected Metric: latency_p99. Path: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.04, with 'lambda_step_readDDB' identified as the root cause and 'lambda_step_readDDB_AWS::Lambda::Function' as the target. The affected metric was 'latency_p99'. The path involved: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB']."
lambda_step_priceGreaterThan55_AWS::Lambda,lambda_step_priceGreaterThan55_AWS::Lambda::Function,latency,0.033544214,latency_Average,"['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']",0_34,"The path of the issue is from StepFnStateMachine76D362E8-T67Tg48ke8oK_client, through AWS::StepFunctions::StateMachine to lambda_step_priceGreaterThan55_AWS::Lambda to lambda_step_priceGreaterThan55_AWS::Lambda::Function to lambda_step_priceGreaterThan55, to Evidently_AWS::Evidently.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.03 was detected. Root Cause Node: lambda_step_priceGreaterThan55_AWS::Lambda::Function, Target Node: lambda_step_priceGreaterThan55_AWS::Lambda, Affected Metric: latency_Average. Path: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.03, with 'lambda_step_priceGreaterThan55_AWS::Lambda::Function' identified as the root cause and 'lambda_step_priceGreaterThan55_AWS::Lambda' as the target. The affected metric was 'latency_Average'. The path involved: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']."
PetSite,PetSearch_AWS::ECS::Fargate,latency,0.090679958,availability_Average,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate']",2_27,"The path of the issue is from PetSite, through petlistadoptions_AWS::ECS::Fargate, to PetSearch_AWS::ECS::Fargate.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.09 was detected. Root Cause Node: PetSearch_AWS::ECS::Fargate, Target Node: PetSite, Affected Metric: availability_Average. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.09, with 'PetSearch_AWS::ECS::Fargate' identified as the root cause and 'PetSite' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate']."
169.254.170.2_remote,PetSearch_AWS::ECS::Fargate,latency,0.08630612,latency_p99,"['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']",0_14,"The path of the issue is from PetSearch_client, through PetSearch_AWS::ECS::Fargate, to 169.254.170.2_remote.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.09 was detected. Root Cause Node: PetSearch_AWS::ECS::Fargate, Target Node: 169.254.170.2_remote, Affected Metric: latency_p99. Path: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.09, with 'PetSearch_AWS::ECS::Fargate' identified as the root cause and '169.254.170.2_remote' as the target. The affected metric was 'latency_p99'. The path involved: ['PetSearch_client', 'PetSearch_AWS::ECS::Fargate', '169.254.170.2_remote']."
lambda_step_readDDB_AWS::Lambda,lambda_step_readDDB_AWS::Lambda::Function,latency,0.114134106,latency_p90,"['lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function']",2_43,The path of the issue is from lambda_step_readDDB_AWS::Lambda to lambda_step_readDDB_AWS::Lambda::Function.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.11 was detected. Root Cause Node: lambda_step_readDDB_AWS::Lambda::Function, Target Node: lambda_step_readDDB_AWS::Lambda, Affected Metric: latency_p90. Path: ['lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.11, with 'lambda_step_readDDB_AWS::Lambda::Function' identified as the root cause and 'lambda_step_readDDB_AWS::Lambda' as the target. The affected metric was 'latency_p90'. The path involved: ['lambda_step_readDDB_AWS::Lambda', 'lambda_step_readDDB_AWS::Lambda::Function']."
AWS::StepFunctions::StateMachine,lambda_step_priceGreaterThan55_AWS::Lambda,latency,0.058212378,latency_p90,"['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']",1_25,The path of the issue is from AWS::StepFunctions::StateMachine to lambda_step_priceGreaterThan55_AWS::Lambda.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.06 was detected. Root Cause Node: lambda_step_priceGreaterThan55_AWS::Lambda, Target Node: AWS::StepFunctions::StateMachine, Affected Metric: latency_p90. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.06, with 'lambda_step_priceGreaterThan55_AWS::Lambda' identified as the root cause and 'AWS::StepFunctions::StateMachine' as the target. The affected metric was 'latency_p90'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']."
lambda_step_priceLessThan55_AWS::Lambda,lambda_step_priceLessThan55_AWS::Lambda::Function,latency,0.090242852,latency_Average,"['lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']",2_34,The path of the issue is from lambda_step_priceLessThan55_AWS::Lambda to lambda_step_priceLessThan55_AWS::Lambda::Function.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.09 was detected. Root Cause Node: lambda_step_priceLessThan55_AWS::Lambda::Function, Target Node: lambda_step_priceLessThan55_AWS::Lambda, Affected Metric: latency_Average. Path: ['lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.09, with 'lambda_step_priceLessThan55_AWS::Lambda::Function' identified as the root cause and 'lambda_step_priceLessThan55_AWS::Lambda' as the target. The affected metric was 'latency_Average'. The path involved: ['lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function']."
PGSQL Query_remote,petlistadoptions_AWS::ECS::Fargate,latency,0.107488243,availability_Average,"['petlistadoptions_AWS::ECS::Fargate', 'PGSQL Query_remote']",1_48,The path of the issue is from petlistadoptions_AWS::ECS::Fargate to PGSQL Query_remote.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.11 was detected. Root Cause Node: petlistadoptions_AWS::ECS::Fargate, Target Node: PGSQL Query_remote, Affected Metric: availability_Average. Path: ['petlistadoptions_AWS::ECS::Fargate', 'PGSQL Query_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.11, with 'petlistadoptions_AWS::ECS::Fargate' identified as the root cause and 'PGSQL Query_remote' as the target. The affected metric was 'availability_Average'. The path involved: ['petlistadoptions_AWS::ECS::Fargate', 'PGSQL Query_remote']."
StepFnStateMachine76D362E8-T67Tg48ke8oK_client,lambda_step_priceLessThan55_AWS::Lambda,latency,0.106527054,availability_Average,"['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55']",2_42,"The path of the issue is from StepFnStateMachine76D362E8-T67Tg48ke8oK_client, through AWS::StepFunctions::StateMachine to lambda_step_priceLessThan55_AWS::Lambda to lambda_step_priceLessThan55_AWS::Lambda::Function, to lambda_step_priceLessThan55.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.11 was detected. Root Cause Node: lambda_step_priceLessThan55_AWS::Lambda, Target Node: StepFnStateMachine76D362E8-T67Tg48ke8oK_client, Affected Metric: availability_Average. Path: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.11, with 'lambda_step_priceLessThan55_AWS::Lambda' identified as the root cause and 'StepFnStateMachine76D362E8-T67Tg48ke8oK_client' as the target. The affected metric was 'availability_Average'. The path involved: ['StepFnStateMachine76D362E8-T67Tg48ke8oK_client', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55']."
lambda_step_readDDB,DynamoDB_AWS::DynamoDB,latency,0.069010133,latency_p95,"['lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']",2_35,The path of the issue is from lambda_step_readDDB to DynamoDB_AWS::DynamoDB.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.07 was detected. Root Cause Node: DynamoDB_AWS::DynamoDB, Target Node: lambda_step_readDDB, Affected Metric: latency_p95. Path: ['lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.07, with 'DynamoDB_AWS::DynamoDB' identified as the root cause and 'lambda_step_readDDB' as the target. The affected metric was 'latency_p95'. The path involved: ['lambda_step_readDDB', 'DynamoDB_AWS::DynamoDB']."
lambda_step_priceGreaterThan55_AWS::Lambda,Evidently_AWS::Evidently,latency,0.061484143,latency_p95,"['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']",2_3,"The path of the issue is from AWS::StepFunctions::StateMachine, through lambda_step_priceGreaterThan55_AWS::Lambda to lambda_step_priceGreaterThan55_AWS::Lambda::Function to lambda_step_priceGreaterThan55, to Evidently_AWS::Evidently.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.06 was detected. Root Cause Node: Evidently_AWS::Evidently, Target Node: lambda_step_priceGreaterThan55_AWS::Lambda, Affected Metric: latency_p95. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.06, with 'Evidently_AWS::Evidently' identified as the root cause and 'lambda_step_priceGreaterThan55_AWS::Lambda' as the target. The affected metric was 'latency_p95'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function', 'lambda_step_priceGreaterThan55', 'Evidently_AWS::Evidently']."
petlistadoptions_client,petlistadoptions_AWS::ECS::Fargate,latency,0.120526767,latency_p90,"['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']",0_30,"The path of the issue is from petlistadoptions_client, through petlistadoptions_AWS::ECS::Fargate to PetSearch_AWS::ECS::Fargate, to AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.12 was detected. Root Cause Node: petlistadoptions_AWS::ECS::Fargate, Target Node: petlistadoptions_client, Affected Metric: latency_p90. Path: ['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.12, with 'petlistadoptions_AWS::ECS::Fargate' identified as the root cause and 'petlistadoptions_client' as the target. The affected metric was 'latency_p90'. The path involved: ['petlistadoptions_client', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']."
petlistadoptions_AWS::ECS::Fargate,PetSite,latency,0.108285305,latency_Average,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'Servi-searc.us-west-2.elb.amazonaws.com_remote']",0_47,"The path of the issue is from PetSite, through petlistadoptions_AWS::ECS::Fargate, to Servi-searc.us-west-2.elb.amazonaws.com_remote.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.11 was detected. Root Cause Node: PetSite, Target Node: petlistadoptions_AWS::ECS::Fargate, Affected Metric: latency_Average. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'Servi-searc.us-west-2.elb.amazonaws.com_remote']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.11, with 'PetSite' identified as the root cause and 'petlistadoptions_AWS::ECS::Fargate' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'Servi-searc.us-west-2.elb.amazonaws.com_remote']."
lambdastatusupdater_AWS::Lambda::Function,petInfo_AWS::DynamoDB::Table,latency,0.063405994,latency_p50,"['lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']",2_26,The path of the issue is from lambdastatusupdater_AWS::Lambda::Function to petInfo_AWS::DynamoDB::Table.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.06 was detected. Root Cause Node: petInfo_AWS::DynamoDB::Table, Target Node: lambdastatusupdater_AWS::Lambda::Function, Affected Metric: latency_p50. Path: ['lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.06, with 'petInfo_AWS::DynamoDB::Table' identified as the root cause and 'lambdastatusupdater_AWS::Lambda::Function' as the target. The affected metric was 'latency_p50'. The path involved: ['lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']."
lambdastatusupdater_AWS::Lambda,lambdastatusupdater_AWS::Lambda::Function,latency,0.128800497,latency_p99,"['lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']",0_36,The path of the issue is from lambdastatusupdater_AWS::Lambda to lambdastatusupdater_AWS::Lambda::Function.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.13 was detected. Root Cause Node: lambdastatusupdater_AWS::Lambda::Function, Target Node: lambdastatusupdater_AWS::Lambda, Affected Metric: latency_p99. Path: ['lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.13, with 'lambdastatusupdater_AWS::Lambda::Function' identified as the root cause and 'lambdastatusupdater_AWS::Lambda' as the target. The affected metric was 'latency_p99'. The path involved: ['lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function']."
amazon.com_remote,payforadoption_AWS::ECS::Container,latency,0.096443409,latency_Average,"['payforadoption_AWS::ECS::Container', 'amazon.com_remote']",1_23,The path of the issue is from payforadoption_AWS::ECS::Container to amazon.com_remote.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.10 was detected. Root Cause Node: payforadoption_AWS::ECS::Container, Target Node: amazon.com_remote, Affected Metric: latency_Average. Path: ['payforadoption_AWS::ECS::Container', 'amazon.com_remote']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.10, with 'payforadoption_AWS::ECS::Container' identified as the root cause and 'amazon.com_remote' as the target. The affected metric was 'latency_Average'. The path involved: ['payforadoption_AWS::ECS::Container', 'amazon.com_remote']."
PetSite,AWS::StepFunctions::StateMachine,latency,0.121426152,latency_p50,"['PetSite', 'AWS::StepFunctions::StateMachine']",1_3,The path of the issue is from PetSite to AWS::StepFunctions::StateMachine.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.12 was detected. Root Cause Node: AWS::StepFunctions::StateMachine, Target Node: PetSite, Affected Metric: latency_p50. Path: ['PetSite', 'AWS::StepFunctions::StateMachine']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.12, with 'AWS::StepFunctions::StateMachine' identified as the root cause and 'PetSite' as the target. The affected metric was 'latency_p50'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine']."
PetSite,AWS::StepFunctions::StateMachine,latency,0.047802814,latency_p90,"['PetSite', 'AWS::StepFunctions::StateMachine']",0_1,The path of the issue is from PetSite to AWS::StepFunctions::StateMachine.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.05 was detected. Root Cause Node: AWS::StepFunctions::StateMachine, Target Node: PetSite, Affected Metric: latency_p90. Path: ['PetSite', 'AWS::StepFunctions::StateMachine']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.05, with 'AWS::StepFunctions::StateMachine' identified as the root cause and 'PetSite' as the target. The affected metric was 'latency_p90'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine']."
lambda_step_priceLessThan55_AWS::Lambda,lambda_step_priceLessThan55_AWS::Lambda::Function,latency,0.039502019,latency_p90,"['AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55', 'Evidently_AWS::Evidently']",2_48,"The path of the issue is from AWS::StepFunctions::StateMachine, through lambda_step_priceLessThan55_AWS::Lambda to lambda_step_priceLessThan55_AWS::Lambda::Function to lambda_step_priceLessThan55, to Evidently_AWS::Evidently.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.04 was detected. Root Cause Node: lambda_step_priceLessThan55_AWS::Lambda::Function, Target Node: lambda_step_priceLessThan55_AWS::Lambda, Affected Metric: latency_p90. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55', 'Evidently_AWS::Evidently']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.04, with 'lambda_step_priceLessThan55_AWS::Lambda::Function' identified as the root cause and 'lambda_step_priceLessThan55_AWS::Lambda' as the target. The affected metric was 'latency_p90'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55', 'Evidently_AWS::Evidently']."
lambda_step_priceGreaterThan55_AWS::Lambda,lambda_step_priceGreaterThan55_AWS::Lambda::Function,latency,0.126628271,latency_p99,"['lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function']",1_49,The path of the issue is from lambda_step_priceGreaterThan55_AWS::Lambda to lambda_step_priceGreaterThan55_AWS::Lambda::Function.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.13 was detected. Root Cause Node: lambda_step_priceGreaterThan55_AWS::Lambda::Function, Target Node: lambda_step_priceGreaterThan55_AWS::Lambda, Affected Metric: latency_p99. Path: ['lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.13, with 'lambda_step_priceGreaterThan55_AWS::Lambda::Function' identified as the root cause and 'lambda_step_priceGreaterThan55_AWS::Lambda' as the target. The affected metric was 'latency_p99'. The path involved: ['lambda_step_priceGreaterThan55_AWS::Lambda', 'lambda_step_priceGreaterThan55_AWS::Lambda::Function']."
lambda_step_priceGreaterThan55_AWS::Lambda,AWS::StepFunctions::StateMachine,latency,0.069715708,latency_p50,"['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']",1_44,The path of the issue is from AWS::StepFunctions::StateMachine to lambda_step_priceGreaterThan55_AWS::Lambda.,2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.07 was detected. Root Cause Node: AWS::StepFunctions::StateMachine, Target Node: lambda_step_priceGreaterThan55_AWS::Lambda, Affected Metric: latency_p50. Path: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.07, with 'AWS::StepFunctions::StateMachine' identified as the root cause and 'lambda_step_priceGreaterThan55_AWS::Lambda' as the target. The affected metric was 'latency_p50'. The path involved: ['AWS::StepFunctions::StateMachine', 'lambda_step_priceGreaterThan55_AWS::Lambda']."
SSM_AWS::SSM,lambda_step_readDDB_AWS::Lambda::Function,latency,0.059548887,availability_Average,"['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'SSM_AWS::SSM']",1_36,"The path of the issue is from lambda_step_readDDB_AWS::Lambda::Function, through lambda_step_readDDB, to SSM_AWS::SSM.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.06 was detected. Root Cause Node: lambda_step_readDDB_AWS::Lambda::Function, Target Node: SSM_AWS::SSM, Affected Metric: availability_Average. Path: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'SSM_AWS::SSM']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.06, with 'lambda_step_readDDB_AWS::Lambda::Function' identified as the root cause and 'SSM_AWS::SSM' as the target. The affected metric was 'availability_Average'. The path involved: ['lambda_step_readDDB_AWS::Lambda::Function', 'lambda_step_readDDB', 'SSM_AWS::SSM']."
petlistadoptions_AWS::ECS::Fargate,PetSite,latency,0.081824187,availability_Average,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate']",0_32,The path of the issue is from PetSite to petlistadoptions_AWS::ECS::Fargate.,2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.08 was detected. Root Cause Node: PetSite, Target Node: petlistadoptions_AWS::ECS::Fargate, Affected Metric: availability_Average. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.08, with 'PetSite' identified as the root cause and 'petlistadoptions_AWS::ECS::Fargate' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate']."
PetSite,lambda_step_priceLessThan55_AWS::Lambda::Function,latency,0.044818926,availability_Average,"['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55', 'Evidently_AWS::Evidently']",0_37,"The path of the issue is from PetSite, through AWS::StepFunctions::StateMachine to lambda_step_priceLessThan55_AWS::Lambda to lambda_step_priceLessThan55_AWS::Lambda::Function to lambda_step_priceLessThan55, to Evidently_AWS::Evidently.",2023-04-18 22:22,"On 2023-04-18 22:22, a latency issue with severity 0.04 was detected. Root Cause Node: lambda_step_priceLessThan55_AWS::Lambda::Function, Target Node: PetSite, Affected Metric: availability_Average. Path: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55', 'Evidently_AWS::Evidently']","On 2023-04-18 22:22, a latency issue was detected. The issue had a severity of 0.04, with 'lambda_step_priceLessThan55_AWS::Lambda::Function' identified as the root cause and 'PetSite' as the target. The affected metric was 'availability_Average'. The path involved: ['PetSite', 'AWS::StepFunctions::StateMachine', 'lambda_step_priceLessThan55_AWS::Lambda', 'lambda_step_priceLessThan55_AWS::Lambda::Function', 'lambda_step_priceLessThan55', 'Evidently_AWS::Evidently']."
AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement,PetSearch_AWS::ECS::Fargate,latency,0.072215032,latency_Average,"['PetSite', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']",2_13,"The path of the issue is from PetSite, through PetSearch_AWS::ECS::Fargate, to AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.07 was detected. Root Cause Node: PetSearch_AWS::ECS::Fargate, Target Node: AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement, Affected Metric: latency_Average. Path: ['PetSite', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.07, with 'PetSearch_AWS::ECS::Fargate' identified as the root cause and 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSite', 'PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']."
AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement,PetSearch_AWS::ECS::Fargate,latency,0.057757014,latency_Average,"['PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']",2_8,The path of the issue is from PetSearch_AWS::ECS::Fargate to AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.06 was detected. Root Cause Node: PetSearch_AWS::ECS::Fargate, Target Node: AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement, Affected Metric: latency_Average. Path: ['PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.06, with 'PetSearch_AWS::ECS::Fargate' identified as the root cause and 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSearch_AWS::ECS::Fargate', 'AWSSimpleSystemsManagement_AWS::AWSSimpleSystemsManagement']."
S3_AWS::S3,petlistadoptions_AWS::ECS::Fargate,latency,0.051209192,latency_p95,"['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'S3_AWS::S3']",1_34,"The path of the issue is from PetSite, through petlistadoptions_AWS::ECS::Fargate to PetSearch_AWS::ECS::Fargate, to S3_AWS::S3.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.05 was detected. Root Cause Node: petlistadoptions_AWS::ECS::Fargate, Target Node: S3_AWS::S3, Affected Metric: latency_p95. Path: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'S3_AWS::S3']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.05, with 'petlistadoptions_AWS::ECS::Fargate' identified as the root cause and 'S3_AWS::S3' as the target. The affected metric was 'latency_p95'. The path involved: ['PetSite', 'petlistadoptions_AWS::ECS::Fargate', 'PetSearch_AWS::ECS::Fargate', 'S3_AWS::S3']."
www.amazon.com_remote,payforadoption_AWS::ECS::Container,latency,0.030734727,latency_p90,"['payforadoption_AWS::ECS::Container', 'www.amazon.com_remote']",2_33,The path of the issue is from payforadoption_AWS::ECS::Container to www.amazon.com_remote.,2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.03 was detected. Root Cause Node: payforadoption_AWS::ECS::Container, Target Node: www.amazon.com_remote, Affected Metric: latency_p90. Path: ['payforadoption_AWS::ECS::Container', 'www.amazon.com_remote']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.03, with 'payforadoption_AWS::ECS::Container' identified as the root cause and 'www.amazon.com_remote' as the target. The affected metric was 'latency_p90'. The path involved: ['payforadoption_AWS::ECS::Container', 'www.amazon.com_remote']."
adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL,payforadoption_AWS::ECS::Container,latency,0.073884204,latency_p90,"['PetSite', 'payforadoption_AWS::ECS::Container', 'adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL']",2_2,"The path of the issue is from PetSite, through payforadoption_AWS::ECS::Container, to adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.07 was detected. Root Cause Node: payforadoption_AWS::ECS::Container, Target Node: adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL, Affected Metric: latency_p90. Path: ['PetSite', 'payforadoption_AWS::ECS::Container', 'adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.07, with 'payforadoption_AWS::ECS::Container' identified as the root cause and 'adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL' as the target. The affected metric was 'latency_p90'. The path involved: ['PetSite', 'payforadoption_AWS::ECS::Container', 'adoptions@services-database.us-west-2.rds.amazonaws.com_Database::SQL']."
PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage,PetSite,latency,0.092158759,latency_Average,"['PetSite', 'payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda']",2_20,"The path of the issue is from PetSite, through payforadoption_AWS::ECS::Container to PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage, to lambdastatusupdater_AWS::Lambda.",2023-04-19 5:27,"On 2023-04-19 5:27, a latency issue with severity 0.09 was detected. Root Cause Node: PetSite, Target Node: PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage, Affected Metric: latency_Average. Path: ['PetSite', 'payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda']","On 2023-04-19 5:27, a latency issue was detected. The issue had a severity of 0.09, with 'PetSite' identified as the root cause and 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage' as the target. The affected metric was 'latency_Average'. The path involved: ['PetSite', 'payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda']."
payforadoption_AWS::ECS::Container,lambdastatusupdater_AWS::Lambda::Function,latency,0.117266002,latency_p50,"['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']",1_46,"The path of the issue is from payforadoption_AWS::ECS::Container, through PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage to lambdastatusupdater_AWS::Lambda to lambdastatusupdater_AWS::Lambda::Function, to petInfo_AWS::DynamoDB::Table.",2023-04-18 21:52,"On 2023-04-18 21:52, a latency issue with severity 0.12 was detected. Root Cause Node: lambdastatusupdater_AWS::Lambda::Function, Target Node: payforadoption_AWS::ECS::Container, Affected Metric: latency_p50. Path: ['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']","On 2023-04-18 21:52, a latency issue was detected. The issue had a severity of 0.12, with 'lambdastatusupdater_AWS::Lambda::Function' identified as the root cause and 'payforadoption_AWS::ECS::Container' as the target. The affected metric was 'latency_p50'. The path involved: ['payforadoption_AWS::ECS::Container', 'PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage', 'lambdastatusupdater_AWS::Lambda', 'lambdastatusupdater_AWS::Lambda::Function', 'petInfo_AWS::DynamoDB::Table']."
